### ISSUE TITLE
images/class-of-2020.jpg sometimes fails to load

### ISSUE THREAD

**Issue by natec425** [jmarsalis/bcca#13]
I'm not entirely sure why, but the images/class-of-2020.jpg sometimes fails to load. I've seen it on multiple devices and browsers.

Even weirder, it seems to load, flash on the screen, and then go away. When I inspect the request in dev tools it shows the HTTP status as `(failed)`. Hovering over `(failed)` shows `net::ERR_SPDY_PROTOCOL_ERROR` in a tooltip.

I didn't have any issue viewing the image locally in development, so I'm wondering if it has something to do with deployment.

Any thoughts?

**Comment by jmarsalis** [comment]
Interesting that you mention this, as I noticed it once or twice several weeks ago as well and simply dismissed it.  I actually got net::ERR_HTTP2_PROTOCOL_ERROR when I was looking at it earlier today.  One post I came across seemed to indicate disk space issues being the culprit, which we were definitely extremely low on.  I just cleared some space, and it is loading fine for me.  Let me know if you see it happen again.
